#!/usr/bin/env bash
set -euo pipefail

# openclaw-snapshot.sh
# Captura automática de contexto e estado do OpenClaw + ambiente

HOME_DIR="/home/opencladio"
MEMORY_DIR="$HOME_DIR/.openclaw/workspace/openclaw_do_maluco/snapshots"
STATE_DIR="$HOME_DIR/.openclaw/workspace/openclaw_do_maluco/workspace/state"
RUNBOOKS_DIR="$HOME_DIR/.openclaw/workspace/openclaw_do_maluco/runbooks"
DATE=$(date +%Y-%m-%d_%H%M%S)

mkdir -p "$MEMORY_DIR" "$STATE_DIR" "$RUNBOOKS_DIR"

SNAP_FILE="$MEMORY_DIR/session_$DATE.md"
STATE_FILE="$STATE_DIR/current.json"

# Capture a basic snapshot
{
  echo "# OpenClaw Session Snapshot - $DATE"
  echo ""
  echo "## User & Host"
  echo "user: $(whoami)"
  echo "host: $(hostname -f)"
  echo "cwd: $(pwd)"
  echo ""
  echo "## Environment (selective)"
  echo "HOME=$HOME"
  echo "OPENCLAW_API_KEY: ${OPENCLAW_API_KEY:+SET}"
  echo "GOG_ACCOUNT: ${GOG_ACCOUNT:-}" 
  echo "GOG_KEYRING_PASSWORD: ${GOG_KEYRING_PASSWORD:+SET}"
  echo ""
  echo "## Services status (OpenClaw & related)"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl --user status openclaw-* --no-pager 2>/dev/null || true
  else
    echo "systemctl unavailable"
  fi
  echo ""
  echo "## Recent commands (filtered)"
  if [ -f "$HOME_DIR/.bash_history" ]; then
    tail -n 200 "$HOME_DIR/.bash_history" | grep -E "(gog|rclone|openclaw|supabase|ssh|systemctl|docker|pm2)" || true
  fi
  echo ""
  echo "## Last logs (OpenClaw gateway)"
  if [ -f "$HOME_DIR/.openclaw/workspace/logs/gateway.log" ]; then
    tail -n 200 "$HOME_DIR/.openclaw/workspace/logs/gateway.log" || true
  else
    echo "gateway.log not found"
  fi
  echo ""
  echo "## Notes"
  echo "Snapshot generated by openclaw-snapshot.sh"
} > "$SNAP_FILE"

# Save state information (hashes and versions)
GOG_CRED_HASH=""
ENV_HASH=""
OPENCLAW_JSON_HASH=""

if [ -f "$HOME_DIR/.config/gogcli/credentials.json" ]; then
  GOG_CRED_HASH=$(md5sum "$HOME_DIR/.config/gogcli/credentials.json" | cut -d' ' -f1)
fi
if [ -f "$HOME_DIR/.openclaw/.env" ]; then
  ENV_HASH=$(md5sum "$HOME_DIR/.openclaw/.env" | cut -d' ' -f1)
fi
if [ -f "$HOME_DIR/.openclaw/openclaw.json" ]; then
  OPENCLAW_JSON_HASH=$(md5sum "$HOME_DIR/.openclaw/openclaw.json" | cut -d' ' -f1)
fi

GOG_VER="$(/home/linuxbrew/.linuxbrew/bin/gog --version 2>/dev/null || echo 'gog-not-found')"
OPENCLAW_VER="$(openclaw --version 2>/dev/null || echo 'openclaw-not-found')"

jq -n \
  --arg date "$DATE" \
  --arg gog_cred "$GOG_CRED_HASH" \
  --arg env_hash "$ENV_HASH" \
  --arg openclaw_json "$OPENCLAW_JSON_HASH" \
  --arg gog_ver "$GOG_VER" \
  --arg openclaw_ver "$OPENCLAW_VER" \
  '{date: $date, gog_credentials_hash: $gog_cred, env_hash: $env_hash, openclaw_json_hash: $openclaw_json, gog_version: $gog_ver, openclaw_version: $openclaw_ver}' \
  > "$STATE_FILE"

# Rotate: keep last 30 snapshots
ls -1tr "$MEMORY_DIR" | head -n -30 | xargs -r -I{} rm -- "$MEMORY_DIR/{}" || true

# Optional: append short marker to daily memory
DAILY_MEM="$HOME_DIR/.openclaw/workspace/memory/$(date +%Y-%m-%d).md"
echo "- Snapshot: $SNAP_FILE" >> "$DAILY_MEM"

echo "Snapshot saved: $SNAP_FILE"

exit 0
